---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/kidsover/public_html/wp-content/themes/child/

    # Sync files with rsync
    - /bin/rsync -avz --delete --exclude '.git' --exclude '.cpanel.yml' --exclude '.env' --exclude 'node_modules' --exclude '.vscode' --exclude '.idea' --exclude 'deploy-files.zip' ./ $DEPLOYPATH

    # Verify critical files were deployed
    - test -f $DEPLOYPATH/functions.php && echo "✓ functions.php deployed" || echo "ERROR: functions.php not deployed"
    - test -f $DEPLOYPATH/style.css && echo "✓ style.css deployed" || echo "ERROR: style.css not deployed"
    - test -d $DEPLOYPATH/css && echo "✓ css directory deployed" || echo "ERROR: css directory not deployed"
    - test -d $DEPLOYPATH/js && echo "✓ js directory deployed" || echo "ERROR: js directory not deployed"
    - test -d $DEPLOYPATH/api && echo "✓ api directory deployed" || echo "ERROR: api directory not deployed"

    # List deployed files for verification
    - echo "CSS files:" && ls -la $DEPLOYPATH/css/ | head -10
    - echo "JS files:" && ls -la $DEPLOYPATH/js/ | head -10

    # Set proper permissions
    - chmod 755 $DEPLOYPATH
    - chmod 644 $DEPLOYPATH/*.php 2>/dev/null || true
    - chmod 644 $DEPLOYPATH/css/*.css 2>/dev/null || true
    - chmod 644 $DEPLOYPATH/js/*.js 2>/dev/null || true
    - chmod 755 $DEPLOYPATH/api 2>/dev/null || true
    - chmod 600 $DEPLOYPATH/api/.env 2>/dev/null || true

    # Log deployment success
    - echo "✓ Deployment completed successfully at $(date)" >> $DEPLOYPATH/deployment.log
    - echo "Git commit: $(git rev-parse --short HEAD)" >> $DEPLOYPATH/deployment.log
    - echo "Branch: $(git branch --show-current 2>/dev/null || echo 'unknown')" >> $DEPLOYPATH/deployment.log
