---
deployment:
  tasks:
    # Deploy all files to the WordPress root directory
    - export DEPLOYPATH=/home/kidsover/public_html/

    # Copy specific directories and files (avoid copying WordPress content snippets)
    - /bin/cp -R api $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -R css $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -R js $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -R images $DEPLOYPATH 2>/dev/null || true
    - /bin/cp *.php $DEPLOYPATH 2>/dev/null || true
    - /bin/cp *.html $DEPLOYPATH 2>/dev/null || true

    # Copy hidden files (except .env which should stay on server only)
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .gitignore $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .env.example $DEPLOYPATH 2>/dev/null || true

    # Ensure config-loader.php is executable and in the right place
    - /bin/cp config-loader.php $DEPLOYPATH 2>/dev/null || true

    # Set proper permissions
    - /bin/chmod 644 $DEPLOYPATH/*.php 2>/dev/null || true
    - /bin/chmod 644 $DEPLOYPATH/.env 2>/dev/null || true

    # Ensure .env exists on server (create from example if missing)
    - test -f $DEPLOYPATH/.env || /bin/cp $DEPLOYPATH/.env.example $DEPLOYPATH/.env

    # Output deployment confirmation
    - echo "Deployment complete. Remember to configure .env with your database credentials if this is first deployment."
